server:
  port: 9000
  servlet:
    context-path: /secureapis

spring:
  application:
    name: secureapis
  datasource:
    url: jdbc:h2:mem:securedb
    driverClassName: org.h2.Driver
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2
# for default implementation without webSecurityConfigurerAdapter
#  security:
#    user:
#      name: jass
#      password: kaur